spring.application.name=Agrocare-BackendWS

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=AGROCARE
spring.datasource.password=Agro1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=MySuperSecretKeyForAgrocareApplication2026
jwt.expiration=86400000

server.port=8080
